import streamlit as st
import openai

# 제목 설정
st.title("Dall-E 이미지 생성기")

# OpenAI API Key 입력 받기
api_key = st.text_input("OpenAI API Key를 입력하세요:", type="password")
if api_key:
    openai.api_key = api_key

# 사용자 프롬프트 입력 받기
prompt = st.text_input("이미지 생성을 위한 프롬프트를 입력하세요:")

# 버튼 클릭 시 이미지 생성
if st.button("Generate Image"):
    if prompt:
        try:
            response = openai.Image.create(
                prompt=prompt,
                n=1,
                size="512x512"
            )
            image_url = response['data'][0]['url']
            st.image(image_url, caption="Generated by Dall-E")
        except Exception as e:
            st.error(f"에러가 발생했습니다: {e}")
    else:
        st.warning("프롬프트를 입력하세요.")
